### ISSUE TITLE
Failed to load the minimap-autohide package

### ISSUE THREAD

**Issue by davidtme** [jayk/minimap-autohide#1]
[Enter steps to reproduce below:]
1. Copy repo into .atom\packages
2. Open atom

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [minimap-autohide](https://github.com/jayk/minimap-autohide) package, v0.10.0
### Stack Trace

Failed to load the minimap-autohide package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\xxx\AppData\Local\atom\app-1.0.0\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\xxx\.atom\packages\minimap-autohide\lib\minimap-autohide.coffee:1:25)
  at Object.<anonymous> (C:\Users\xxx\.atom\packages\minimap-autohide\lib\minimap-autohide.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\xxx\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\xxx\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:709:34)
  at C:\Users\xxx\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:188:28
  at Package.module.exports.Package.measure (C:\Users\xxx\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:165:15)
  at Package.module.exports.Package.load (C:\Users\xxx\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:179:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\xxx\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:372:14)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\xxx\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:336:14)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\xxx\AppData\Local\atom\app-1.0.0\resources\app.asar\src\atom.js:638:21)
  at Object.<anonymous> (C:\Users\xxx\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\xxx\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\xxx\AppData\Local\atom\app-1.0.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///C:/Users/xxx/AppData/Local/atom/app-1.0.0/resources/app.asar/static/index.js:96:23)
  at window.onload (file:///C:/Users/xxx/AppData/Local/atom/app-1.0.0/resources/app.asar/static/index.js:36:7)

```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-yeoman, v0.3.11
linter, v1.1.0
minimap, v4.10.2
minimap-autohide, v0.10.0
minimap-git-diff, v4.1.3
omnisharp-atom, v0.17.3

# Dev
No dev packages
```

**Comment by jayk** [comment]
Please try again with 0.10.1 version.  This depends on event-kit which minimap also depends on.  It should be present on your system.
